language: node_js
node_js:
  - "lts/*"

before_script:
  - gem install awesome_bot

script:
  - npm run lint
  - awesome_bot public/logos/**/*.json --allow-redirect --allow-dupe --white-list bjork.com
