language: node_js
node_js:
  - 'lts/*'

stages:
  - Checks

jobs:
  include:
    - stage: Checks
      script:
        - gem install awesome_bot
        - awesome_bot *.md --allow-redirect --white-list travis-ci,packagephobia.now
      name: Check Doc links

    - script: npm run check-formatting
      name: Check Formatting

    - script: npm run lint
      name: Lint
